project/emp/urls.py
from django.urls import path,URLPattern
from emp import views
from django.contrib import admin

urlpatterns=[
    path('admin/',admin.site.urls),
    path('',views.show),
    path('show',views.show),
    path('emp',views.emp),
    path('edit/<int:id>',views.edit),
    path('update/<int:id>',views.update),
    path('delete/<int:id>',views.destroy),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("emp.urls")),
]

project/emp/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    class Meta:
        db_table="employ"

project/emp/forms.py
from django import forms
from emp.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"


project/emp/views.py
from django.shortcuts import render,redirect
from emp.forms import EmployeeForm
from emp.models import Employee

# Create your views here.
def emp(request):
    if request.method == "POST":
        form= EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request,"index.html",{'form':form})

def show(request):
    employees=Employee.objects.all()
    return render(request,"show.html",{'employees': employees })

def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request,"edit.html",{'employee':employee})

def update(request, id):
    employee = Employee.objects.get(id=id)
    form =EmployeeForm(request.POST,instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request,"edit.html",{'employee':employee})
            
def destroy(request, id):
    employee =Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")


project/emp/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css1/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
    <form action="/update/{{employee.id}}" method="post">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Id</label>
                <div class="col-sm-4">
                    <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Name</label>
                <div class="col-sm-4">
                    <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email</label>
                <div class="col-sm-4">
                    <input type="email" name="eemail" id="id_eemail" 
                        value="{{ employee.eemail }}">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact</label>
                <div class="col-sm-4">
                    <input type="text" name="econtact" id="id_econtact" required maxlength="15"
                        value="{{ employee.econtact }}">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

project/emp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css1/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <form method="post" class="post-form" action="/emp">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label for="" class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Enter Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Employee Id: </label>
            <div class="col-sm-4">
                {{ form.eid }}
            </div>
        </div>
        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Employee Name: </label>
            <div class="col-sm-4">
                {{ form.ename }}
            </div>
        </div>
        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Employee Email: </label>
            <div class="col-sm-4">
                {{ form.eemail }}
            </div>
        </div>
        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Employee Contact: </label>
            <div class="col-sm-4">
                {{ form.econtact }}
            </div>
        </div>
        <div class="form-group row">
            <label for="" class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

project/emp/templates/show.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee record</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css1/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
    <table class="container mt-3 table table-stripped table-bordered table-warning table-lg">
        <thead class="thead-dark">
            <tr>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Employee Email</th>
                <th>Employee Contact</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
        <tr>
            
            <td>{{ employee.eid }}</td>
            <td>{{ employee.ename }}</td>
            <td>{{ employee.eemail }}</td>
            <td>{{ employee.econtact }}</td>
            <td>
                <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                <a href="/delete/{{ employee.id }}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    <br>
    <br>
    <center><a href="/emp" class="btn btn-primary">Add New record</a></center>
</body>
</html>